### ISSUE TITLE
doc: add a JQ example

### ISSUE THREAD

**Issue by pozil** [Force-Config-Control/lightning-flow-scanner-sfdx#16]
Having a CLI that generates JSON is powerful for automating certain tasks (CI and more). You can easily parse the JSON output with the [JQ utility](https://stedolan.github.io/jq/) so I think that it's interesting to show a small script example in the readme that demonstrates this:

```sh
#!/bin/bash

json=$(sfdx flow:scan)
flowCount=$(echo $json | jq '.summary.totalFlows')
errorCount=$(echo $json | jq '.summary.totalResults')
echo "Scanned $flowCount flows"
echo "Found $errorCount errors"
```

**Comment by RubenHalman** [comment]
I will close this for now but take this inconsideration

**Comment by RubenHalman** [comment]
@pozil It seems this one got overlooked and possibly replaced by other priorities, my apologies. I've re-opened this and will aim to (re) add JQ examples to the docs.
