### ISSUE TITLE
How to enable .flowscanignore and other questions

### ISSUE THREAD

**Issue by jorgesolebur** [Force-Config-Control/lightning-flow-scanner-sfdx#28]
Hello

First of all thanks for the contribution, this is really great !!
I want to enable only some rules from the plugin, so I want to use a  .flowscanignore. I have place this file in the root of my project, but when I run sfdx flow:scan it does not seem to take it into account. Am I missing anything? 

Another question I have: by default, if you dont specify the username u, the plugin is scanning the flows that are stored locally right? How do you specify whcih folder to scan? I dont see that parameter in flow:scan command.

Thanks in advance for the support !

**Comment by jorgesolebur** [comment]
Hey! Quick update! The .flowIgnore file is now working fine. However I would like to confirm with you that if we do not specify the -u target org parameter when calling flow:scan, which local folder does this tool uses to scan for flows? Can we specify the folder?

Thanks!

**Comment by jorgesolebur** [comment]
Ok I checked your code and found it - using parameter -d ! You can probably update the documentation for others to check it next time faster ! :-) Thanks

**Comment by RubenHalman** [comment]
Hey @jorgesolebur. Sorry for my slow response, glad to hear you got it working. I am planning to spend more time on the SFDX plugin soon, after fixing some issues in the core module and implementing proper error handling. I wiill definitely also take this feedback into account with regards to documentation, thanks a lot!

**Comment by jorgesolebur** [comment]
@RubenHalman  quick question any way I can install this plugins without the prompt? 
When I run sfdx plugins:install lightning-flow-scanner I got the warning that sayd that this plugins is not digitally signed and it asks me if I really want to install it. Do you know if there is a way, directly from the sfdx:install command, to force the installation? I tried --force but does not work. 

I need this to be installed automatically as part of my CI job, this is why it needs to be completely automated,

**Comment by RubenHalman** [comment]
Salesforce is working on that, but for now you would need to use something like this in a bash script to handle this error:

echo 'y' | sfdx plugins:install yourpluginname

**Comment by jorgesolebur** [comment]
It works - thanks again for the workaround. I was taking instead this path https://developer.salesforce.com/blogs/2017/10/salesforce-dx-cli-plugin-update but dont think it was really necessary.

**Comment by RubenHalman** [comment]
@jorgesolebur Glad to hear you got it working. I'm working on some improvements, would love to hear any success/failures/necessary improvements and alike, thanks a lot!
