### ISSUE TITLE
Add a flag to scan only one flow

### ISSUE THREAD

**Issue by davidbrowaeys** [Force-Config-Control/lightning-flow-scanner-sfdx#31]
It would be good to add an option to scan a single flow or a list (comma separated) or ultimately based on a manifest (package.xml). 

```
sfdx flow:scan -p force-app/main/default/flows/Myflow1.flow-meta.xml,orce-app/main/default/flows/Myflow2.flow-meta.xml
sfdx flow:scan -x package.xml
```

**Comment by davidbrowaeys** [comment]
A potential proposed fix if you are interested: https://github.com/Force-Config-Control/lightning-flow-scanner-sfdx/pull/32

**Comment by RubenHalman** [comment]
Hi David thank you for your contribution and sorry for my slow response. I'll merge the change.
