### ISSUE TITLE
Is the repo still maintained ?

### ISSUE THREAD

**Issue by nvuillam** [Force-Config-Control/lightning-flow-scanner-sfdx#33]
Hi @RubenHalman 

I'd like to add flow scanner within [MegaLinter](https://megalinter.io/latest/)

I see there is not commit for more than one year

Is the repo still maintained ?

If not, can we discuss about an option I can think about to revive it ?

Many thanks & Best regards

Nicolas

**Comment by RubenHalman** [comment]
Hi thank you for reaching out. I would definitely want to support that effort and keep maintaining the project. So far I believe the adoption is fairly low and I haven't personally needed any further modifications but I'm open to suggestions.
