### ISSUE TITLE
Implement severity level for issues

### ISSUE THREAD

**Issue by nvuillam** [Force-Config-Control/lightning-flow-scanner-sfdx#39]
Let's follow [SARIF level values](https://github.com/microsoft/sarif-tutorials/blob/main/docs/2-Basics.md#level):
- error
- warning
- note

The level of an issue must be overridable in configuration file

**Comment by RubenHalman** [comment]
@nvuillam is it okay if the config file looks like:
`{
 "rules": [
     {
          "ruleName": "UnusedVariables",
          "severity": "warning"
    }
 ],
  "exceptions": [
    {
      "flowName": "GetAccounts",
      "results": [
        {
          "ruleName": "UnusedVariables",
          "result": "somecount"
        }
      ]
    }
  ]
}`

**Comment by nvuillam** [comment]
The best would be to follow eslitn-like format

```json
"rules": {
    "ruleId1": {
        "severity": "warning"
    },
   "ruleId2": {
        "severity": "error"
    }
}
```

ex: https://eslint.org/docs/latest/use/configure/configuration-files#comments-in-configuration-files
