### ISSUE TITLE
HardcodedIds false positive

### ISSUE THREAD

**Issue by Damecek** [Force-Config-Control/lightning-flow-scanner-sfdx#43]
This rule `HardcodedIds` falsely identified a screen element, where we have a display text component with an image, where the url contained a Salesforce Id.

This is the identified element
```xml
<screens>
    <name>Submit_RMA</name>
    <label>Submit RMA</label>
    <locationX>840</locationX>
    <locationY>206</locationY>
    <allowBack>false</allowBack>
    <allowFinish>true</allowFinish>
    <allowPause>false</allowPause>
    <connector>
        <targetReference>RMA_Form</targetReference>
    </connector>
    <fields>
        <name>intro5</name>
        <fieldText><img src="https://asd.file.force.com/sfc/servlet.shepherd/version/download/0681x000003Q4yH?asPdf=false&operationContext=CHATTER" alt="image.png"></fieldText>
        <fieldType>DisplayText</fieldType>
    </fields>
    <nextOrFinishButtonLabel>Next</nextOrFinishButtonLabel>
    <showFooter>true</showFooter>
    <showHeader>false</showHeader>
</screens>
```

**Comment by Damecek** [comment]
I believe this is an image stored in production as a file, with public url exposed.

**Comment by RubenHalman** [comment]
That is fine, but it would still be an ID that can break.(let's say you are migrating to a different prod org). Im open to a debate on this and if you feel this should not give an error you can create an exception using the configuration file, but I do believe the warning is 'correct' and the it could technically be improved upon

**Comment by Damecek** [comment]
I think you are right, let's keep the current behavior.
