### ISSUE TITLE
Implement test classes to check compilation & arguments

### ISSUE THREAD

**Issue by nvuillam** [Force-Config-Control/lightning-flow-scanner-sfdx#53]

**Comment by RubenHalman** [comment]
there are test classes that check rules and they are in the core module, like the rules are.

**Comment by nvuillam** [comment]
@RubenHalman we should also add at least on test job in this repo's CI so we can be sure it compiles and nothing in broken ^^

So not a test class for each rule obviously, but someto check:
- that a human result is output
- that a json result is output
- check thresold are taken in account
- check that configuration is taken in account
- etc... :)

But it's not that urgent :)
