### ISSUE TITLE
0 errors when running from command line

### ISSUE THREAD

**Issue by bilalelaly** [Force-Config-Control/lightning-flow-scanner-sfdx#75]
When running the commands from the command line I get 0 errors :
![image](https://github.com/Force-Config-Control/lightning-flow-scanner-sfdx/assets/32270257/1b7acecb-4f16-438e-9e76-6a59c4069228)

However, when I run the command directly from the VSCode Extension I get plenty of errors on the 123 flows.
Any idea on where this issue could come from ? 

Thanks!

**Comment by RubenHalman** [comment]
Long story short. My suspicion is that your package manager accidentally upgraded a dependency (more specifically the dependency of the core module that performs the scan) which is not yet supported by the sfdx plugin. I applied some configuration that should prevent this from happening on your end in future versions, however, you will probably either need to reinstall the sfdx plugin or its dependencies(node modules) to resolve this. Please let me know if that helps!
